Correção de relações e adição de mais algumas
lmtsufape/hvu pull request #134
Opened 2024-01-23 18:12 UTC by MESTREGUGABr

2024-01-23 20:15 UTC, ines-alessandra requested changes
refaça as pendencias marcadas

2024-01-23 20:15 UTC, ines-alessandra commented on back/src/main/java/br/edu/ufape/hvu/controller/dto/request/ExameMicroscopicoRequest.java
não é para add model.Foto e sim FotoRequest, igual a EtapaRequest

2024-01-23 20:15 UTC, ines-alessandra commented on back/src/main/java/br/edu/ufape/hvu/controller/dto/request/MedicoRequest.java
aqui também deve ser colocado InstituicaoRequest e não model.Instituicao

2024-01-23 20:15 UTC, ines-alessandra commented on back/src/main/java/br/edu/ufape/hvu/controller/dto/response/ExameMicroscopicoResponse.java
já aqui é para ser add FotoResponse

2024-01-23 20:15 UTC, ines-alessandra commented on back/src/main/java/br/edu/ufape/hvu/controller/dto/response/MedicoResponse.java
e aqui InstituicaoResponse

2024-01-24 12:40 UTC, MESTREGUGABr commented
@ines-alessandra creio que foram resolvidas as alterações que você colicitou

2024-01-25 20:46 UTC, merged